In [21]:
import numpy as np
import pandas as pd

In [24]:
df1 = pd.read_csv("E:\Git_repo\ComputerStoreDataset\dirty_data.csv")
df2 = pd.read_csv("E:\Git_repo\ComputerStoreDataset\missing_data.csv")

<>:1: SyntaxWarning: invalid escape sequence '\G'
<>:2: SyntaxWarning: invalid escape sequence '\G'
<>:1: SyntaxWarning: invalid escape sequence '\G'
<>:2: SyntaxWarning: invalid escape sequence '\G'
C:\Users\risha\AppData\Local\Temp\ipykernel_16424\3203029369.py:1: SyntaxWarning: invalid escape sequence '\G'
  df1 = pd.read_csv("E:\Git_repo\ComputerStoreDataset\dirty_data.csv")
C:\Users\risha\AppData\Local\Temp\ipykernel_16424\3203029369.py:2: SyntaxWarning: invalid escape sequence '\G'
  df2 = pd.read_csv("E:\Git_repo\ComputerStoreDataset\missing_data.csv")

In [25]:
df1.describe()

,order_price,delivery_charges,customer_lat,customer_long,coupon_discount,order_total,distance_to_nearest_warehouse
count,500.000000,500.000000,500.000000,500.000000,500.000000,5.000000e+02,500.000000
mean,25522.216000,76.658200,-35.835234,144.969494,10.890000,3.920967e+04,2.204224
std,86333.729169,14.481465,12.045393,0.022720,8.649134,2.741940e+05,8.812416
min,585.000000,46.350000,-37.827123,144.924967,0.000000,6.392900e+02,0.107800
25%,7050.000000,65.982500,-37.818222,144.953488,5.000000,6.454735e+03,0.751425
50%,12807.500000,76.310000,-37.812165,144.965357,10.000000,1.129396e+04,1.030100
75%,20360.000000,82.555000,-37.805364,144.983985,15.000000,1.811919e+04,1.408625
max,947691.000000,114.040000,37.826339,145.019837,25.000000,5.688270e+06,94.973400

In [5]:
df1.head()

,order_id,customer_id,date,nearest_warehouse,shopping_cart,order_price,delivery_charges,customer_lat,customer_long,coupon_discount,order_total,season,is_expedited_delivery,distance_to_nearest_warehouse,latest_customer_review,is_happy_customer
0,ORD182494,ID6197211592,2019-06-22,Thompson,"[('Lucent 330S', 1), ('Thunder line', 2), ('iS...",12200,79.89,-37.815105,144.932843,10,11059.89,Winter,True,1.2800,perfect phone and trusted seller. phone itself...,True
1,ORD395518,ID0282825849,2019-12-29,Thompson,"[('Thunder line', 1), ('Universe Note', 2)]",9080,62.71,-37.802736,144.951118,0,9142.71,Summer,False,1.1621,it keeps dropping calls the wifi don't work th...,False
2,ORD494479,ID0579391891,2019-03-02,Nickolson,"[('Thunder line', 1), ('pearTV', 2)]",10670,65.87,-37.821302,144.957581,10,9668.87,Autumn,False,1.0949,five stars this is a great cheap phone.,True
3,ORD019224,ID4544561904,2019-01-12,Nickolson,"[('Universe Note', 1), ('Alcon 10', 2), ('Oliv...",24800,57.61,-37.811416,144.973073,15,21137.61,Summer,False,0.8571,charger did not fit the charger didn't fit.,False
4,ORD104032,ID6231506320,2019-11-28,Nickolson,"[('Universe Note', 1), ('Olivia x460', 1), ('i...",9145,75.54,37.823859,144.969892,25,6934.29,Spring,False,0.5867,four stars good,True

In [7]:
df1.columns

Index(['order_id', 'customer_id', 'date', 'nearest_warehouse', 'shopping_cart',
       'order_price', 'delivery_charges', 'customer_lat', 'customer_long',
       'coupon_discount', 'order_total', 'season', 'is_expedited_delivery',
       'distance_to_nearest_warehouse', 'latest_customer_review',
       'is_happy_customer'],
      dtype='object')

In [27]:
df1.isna().sum()

order_id                         0
customer_id                      0
date                             0
nearest_warehouse                0
shopping_cart                    0
order_price                      0
delivery_charges                 0
customer_lat                     0
customer_long                    0
coupon_discount                  0
order_total                      0
season                           0
is_expedited_delivery            0
distance_to_nearest_warehouse    0
latest_customer_review           1
is_happy_customer                0
dtype: int64

In [11]:
df1['order_price'].describe()

count       500.000000
mean      25522.216000
std       86333.729169
min         585.000000
25%        7050.000000
50%       12807.500000
75%       20360.000000
max      947691.000000
Name: order_price, dtype: float64

In [18]:
df1['shopping_cart']

0      [('Lucent 330S', 1), ('Thunder line', 2), ('iS...
1            [('Thunder line', 1), ('Universe Note', 2)]
2                   [('Thunder line', 1), ('pearTV', 2)]
3      [('Universe Note', 1), ('Alcon 10', 2), ('Oliv...
4      [('Universe Note', 1), ('Olivia x460', 1), ('i...
                             ...
495               [('Alcon 10', 2), ('iAssist Line', 2)]
496    [('pearTV', 2), ('Candle Inferno', 2), ('Toshi...
497    [('pearTV', 1), ('Alcon 10', 1), ('Lucent 330S...
498    [('iStream', 1), ('Candle Inferno', 1), ('iAss...
499    [('iStream', 1), ('Toshika 750', 1), ('Alcon 1...
Name: shopping_cart, Length: 500, dtype: object

In [19]:
df1['c'] = df['shopping_cart'].str.replace("('", "{\"items\": ")

In [20]:
df.head()

,order_id,customer_id,date,nearest_warehouse,shopping_cart,order_price,delivery_charges,customer_lat,customer_long,coupon_discount,order_total,season,is_expedited_delivery,distance_to_nearest_warehouse,latest_customer_review,is_happy_customer,c
0,ORD182494,ID6197211592,2019-06-22,Thompson,"[('Lucent 330S', 1), ('Thunder line', 2), ('iS...",12200,79.89,-37.815105,144.932843,10,11059.89,Winter,True,1.2800,perfect phone and trusted seller. phone itself...,True,"[{""items"": Lucent 330S', 1), {""items"": Thunder..."
1,ORD395518,ID0282825849,2019-12-29,Thompson,"[('Thunder line', 1), ('Universe Note', 2)]",9080,62.71,-37.802736,144.951118,0,9142.71,Summer,False,1.1621,it keeps dropping calls the wifi don't work th...,False,"[{""items"": Thunder line', 1), {""items"": Univer..."
2,ORD494479,ID0579391891,2019-03-02,Nickolson,"[('Thunder line', 1), ('pearTV', 2)]",10670,65.87,-37.821302,144.957581,10,9668.87,Autumn,False,1.0949,five stars this is a great cheap phone.,True,"[{""items"": Thunder line', 1), {""items"": pearTV..."
3,ORD019224,ID4544561904,2019-01-12,Nickolson,"[('Universe Note', 1), ('Alcon 10', 2), ('Oliv...",24800,57.61,-37.811416,144.973073,15,21137.61,Summer,False,0.8571,charger did not fit the charger didn't fit.,False,"[{""items"": Universe Note', 1), {""items"": Alcon..."
4,ORD104032,ID6231506320,2019-11-28,Nickolson,"[('Universe Note', 1), ('Olivia x460', 1), ('i...",9145,75.54,37.823859,144.969892,25,6934.29,Spring,False,0.5867,four stars good,True,"[{""items"": Universe Note', 1), {""items"": Olivi..."

In [33]:
#merged = pd.merge(df1, df2, on='order_id', how='outer')

In [34]:
import os

In [37]:
files = os.listdir('E:/Git_repo/ComputerStoreDataset')

In [38]:
print(files)

['dirty_data.csv', 'missing_data.csv', 'warehouses.csv']

In [48]:
df_concat = pd.DataFrame()

for file in files:
    if ((file[0] == 'm') | (file[0] == 'd')):
         df = pd.read_csv('E:/Git_repo/ComputerStoreDataset/'+file)
         df_concat = pd.concat([df_concat, df])

In [50]:
df_concat.shape

(1000, 16)

In [51]:
df_concat.sample(20)

,order_id,customer_id,date,nearest_warehouse,shopping_cart,order_price,delivery_charges,customer_lat,customer_long,coupon_discount,order_total,season,is_expedited_delivery,distance_to_nearest_warehouse,latest_customer_review,is_happy_customer
29,ORD406814,ID0452381262,2019-03-01,Thompson,"[('Thunder line', 2), ('Toshika 750', 1), ('pe...",21730.0,69.68,-37.825343,144.951318,10,19626.68,Autumn,False,1.4590,"good phone... obviously, this isn't a newer pi...",True
403,ORD363836,ID0746922230,2019-06-29,Nickolson,"[('Candle Inferno', 1), ('Olivia x460', 1), ('...",4115.0,79.85,-37.823958,144.982647,5,3989.10,Winter,True,1.2971,five stars excellent piece! struggling to slee...,True
75,ORD070810,ID0317369540,2019-02-22,Thompson,"[('Olivia x460', 1), ('Candle Inferno', 1), ('...",14275.0,77.18,-37.806224,144.955466,15,12210.93,Summer,False,1.0299,is really good and i like it i got tired from ...,True
302,ORD151900,ID0576873448,2019-02-10,Bakers,"[('Alcon 10', 2), ('iAssist Line', 1), ('Unive...",28250.0,100.04,-37.824252,144.990037,25,21287.54,Summer,True,1.6514,my favorite smart phone my favorite smart phon...,True
223,ORD119688,ID4061053480,2019-12-08,Bakers,"[('Alcon 10', 2), ('iAssist Line', 1), ('Olivi...",21350.0,71.38,-37.810045,144.995853,10,19286.38,Summer,True,0.0549,two stars bad quality screen,False
264,ORD374251,ID0702363476,2019-03-03,Thompson,"[('Lucent 330S', 1), ('iAssist Line', 1), ('Ol...",4680.0,80.02,-37.806300,144.941601,15,4058.02,Autumn,True,0.8570,great deal. excellent on all counts. and far m...,False
22,ORD277791,ID5299391822,2019-07-26,Thompson,"[('Olivia x460', 2), ('Lucent 330S', 1), ('Uni...",7130.0,49.53,-37.811422,144.936692,15,6110.03,Winter,False,0.9232,one star i never used this phone since i bough...,NaN
40,ORD466433,ID3218293544,2019-03-08,Thompson,"[('pearTV', 1), ('Olivia x460', 1)]",7535.0,66.54,-37.804025,144.952851,25,5717.79,Autumn,False,1.1956,great phone! ordered for my 77 year old mom. s...,True
286,ORD004848,ID0589421007,2019-05-15,Nickolson,"[('Olivia x460', 2), ('pearTV', 2)]",15070.0,79.13,-37.809628,144.972568,5,14395.63,Autumn,True,1.0328,thx you the phone was like new and everything ...,True
128,ORD471978,ID6197211588,2019-03-13,Thompson,"[('pearTV', 1), ('iAssist Line', 2), ('Alcon 1...",24070.0,66.85,-37.814980,144.932788,25,18119.35,Autumn,False,1.2819,excellent conditions it is working very well.,True
410,ORD122150,ID0248746924,2019-01-20,Bakers,"[('Thunder line', 1), ('iStream', 2), ('Lucent...",3710.0,87.61,-37.825482,144.996216,15,3241.11,Summer,True,1.7261,don't buy phones through digico received a pre...,False
304,ORD267476,ID4716795474,2019-09-10,Thompson,"[('Lucent 330S', 1), ('Candle Inferno', 1)]",1660.0,76.92,-37.818757,144.953426,5,1653.92,Spring,False,0.8782,great value great used phone,True
422,ORD148182,ID0591435914,2019-10-18,Nickolson,"[('Universe Note', 1), ('iStream', 1)]",3600.0,97.66,-37.818738,144.967061,0,3697.66,Spring,True,0.2195,this is a great tablet for the price i paid. m...,True
212,ORD232552,ID0591258186,2019-05-27,Thompson,"[('pearTV', 1), ('Olivia x460', 2), ('Thunder ...",13120.0,50.92,-37.824242,144.953832,0,13170.92,Autumn,False,1.4185,thought it would be more powerful and have a l...,False
27,ORD126262,ID1495248920,2019-08-19,Nickolson,"[('Alcon 10', 1), ('Thunder line', 2), ('iAssi...",20210.0,57.97,-37.819406,144.963803,25,15215.47,Winter,True,0.5135,useless battery the battery life is ridiculous...,False
137,ORD049050,ID0775942584,2019-10-05,Thompson,"[('iStream', 2), ('Olivia x460', 2)]",2750.0,107.97,-37.805416,144.961520,25,2170.47,Spring,True,1.5060,"this is my second inferno, i'm upgrading from ...",True
38,ORD000459,ID0317369535,2019-12-17,Thompson,"[('Lucent 330S', 1), ('Alcon 10', 2), ('Candle...",25870.0,75.14,-37.807078,144.955667,25,19477.64,Summer,False,0.9796,i bought these as a starter online browser. it...,True
136,ORD197167,ID0377544391,09/04/2019,Thompson,"[('Thunder line', 2), ('Alcon 10', 1), ('Lucen...",23180.0,64.98,-37.815584,144.945277,25,17449.98,Autumn,False,0.3603,super phone within days of receiving this phon...,True
23,ORD344823,ID6167344543,2019-04-17,Nickolson,"[('Alcon 10', 2), ('Thunder line', 1)]",20080.0,63.31,-37.811742,144.970260,15,17131.31,Autumn,False,0.7654,four stars nice phone,True
270,ORD160120,ID1497170573,2019-05-25,Bakers,"[('Toshika 750', 2), ('iAssist Line', 2)]",13090.0,53.95,-37.823615,144.990227,25,9871.45,Autumn,False,NaN,hot trash! this phone is horrible do not buy! ...,False

In [53]:
df_concat.dtypes

order_id                          object
customer_id                       object
date                              object
nearest_warehouse                 object
shopping_cart                     object
order_price                      float64
delivery_charges                 float64
customer_lat                     float64
customer_long                    float64
coupon_discount                    int64
order_total                      float64
season                            object
is_expedited_delivery               bool
distance_to_nearest_warehouse    float64
latest_customer_review            object
is_happy_customer                 object
dtype: object

In [54]:
df['shopping_cart'] = (
    df['shopping_cart']
      .str.replace('(', '{')
      .str.replace(')', '}')
      .str.replace("'", " ")
)

In [75]:
df.loc['order_id']

KeyError: 'order_id'

In [69]:
df[['order_id','date']].sort_values('order_id')

      order_id        date
38   ORD000459  2019-12-17
362  ORD003106  2019-08-18
61   ORD004228  2019-10-12
95   ORD004262  2019-06-23
5    ORD005004  2019-05-07
..         ...         ...
238  ORD495321  2019-05-02
321  ORD496151  2019-12-23
130  ORD498065  2019-11-17
206  ORD498344  2019-08-24
168  ORD498853  2019-08-17

[500 rows x 2 columns]

In [65]:
df.query(
    "order_id.str.contains('2112')")

,order_id,customer_id,date,nearest_warehouse,shopping_cart,order_price,delivery_charges,customer_lat,customer_long,coupon_discount,order_total,season,is_expedited_delivery,distance_to_nearest_warehouse,latest_customer_review,is_happy_customer
0,ORD382112,ID0289597187,2019-03-06,Thompson,"[{ pearTV , 1}, { Candle Inferno , 2}]",7170.0,61.72,-37.811782,144.951972,15,6156.22,Autumn,True,0.4425,"to many adds in ui it has adds, sends info to ...",False